name: Checkmarx AST Scan
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          cx_tenant: ast_integration_tenant_eu
          base_uri: https://eu.ast.checkmarx.net
          additional_params: --debug --apikey ${{ secrets.APIKEY }}
